import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.utils import formataddr

def _build_html_email(report_data, html_body, lang):
    """Build a professional HTML email body."""
    customer_name = report_data.get('customer_name', 'Seeker')
    dream_title = report_data.get('dream_title', 'Your Dream Analysis Report')
    header_logo_b64 = report_data.get('header_logo_b64', '')
    session_url = report_data.get('session_url', '')
    cta_link = report_data.get('cta_link', session_url)
    order_data = report_data.get('order_data', None)

    # Order confirmation section (optional)
    order_html = ''
    if order_data:
        plan_label = order_data.get('plan_type', 'Plan')
        amount = order_data.get('amount', 0)
        currency = order_data.get('currency', 'USD')
        order_id = order_data.get('order_id', '')
        status = order_data.get('status', 'completed')
        status_text = status.upper() if isinstance(status, str) else 'COMPLETED'
        order_html = f"""
        <div style="background:rgba(124,92,255,0.08);border:1px solid rgba(124,92,255,0.2);border-radius:12px;padding:20px;margin:24px 0;">
            <h3 style="margin:0 0 12px;font-size:14px;color:#b8a6ff;">{ 'Order Confirmation' if lang == 'en' else '订单确认' }</h3>
            <p style="margin:4px 0;font-size:13px;color:#aaa;"><strong>{ 'Plan:' if lang == 'en' else '套餐：' }</strong> {plan_label}</p>
            <p style="margin:4px 0;font-size:13px;color:#aaa;"><strong>{ 'Amount:' if lang == 'en' else '金额：' }</strong> ${amount:.2f} {currency}</p>
            <p style="margin:4px 0;font-size:13px;color:#aaa;"><strong>{ 'Order ID:' if lang == 'en' else '订单号：' }</strong> {order_id}</p>
            <p style="margin:4px 0;font-size:13px;color:#aaa;"><strong>{ 'Status:' if lang == 'en' else '状态：' }</strong> {status_text}</p>
        </div>
        """

    # Header logo
    logo_html = ''
    if header_logo_b64:
        logo_html = f'<img src="{header_logo_b64}" alt="Subconscious Mirror" style="height:48px;margin-bottom:16px;"/>'

    # CTA button
    cta_html = ''
    if cta_link:
        cta_text = 'View Full Report' if lang == 'en' else '查看完整报告'
        cta_html = f"""
        <div style="text-align:center;margin:28px 0;">
            <a href="{cta_link}" style="display:inline-block;padding:12px 28px;background:linear-gradient(135deg,#7c5cff,#5b3cc4);color:#fff;text-decoration:none;border-radius:24px;font-size:13px;font-weight:600;">{cta_text}</a>
        </div>
        """

    footer_note = "This report was generated by Subconscious Mirror AI. It is for self-exploration and entertainment purposes only." if lang == 'en' else "本报告由潜意识之镜 AI 生成，仅供自我探索与娱乐参考。"

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{dream_title}</title>
<style>
    body {{ margin:0; padding:0; background:#0a0a12; font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }}
    .container {{ max-width:640px; margin:0 auto; background:#111122; border:1px solid rgba(255,255,255,0.08); border-radius:18px; overflow:hidden; }}
    .header {{ background:linear-gradient(135deg, rgba(124,92,255,0.2), rgba(124,92,255,0.05)); padding:32px; text-align:center; border-bottom:1px solid rgba(255,255,255,0.06); }}
    .header h1 {{ margin:0; font-size:22px; color:#fff; font-weight:600; font-style:italic; }}
    .header p {{ margin:10px 0 0; font-size:13px; color:#aaa; }}
    .body {{ padding:32px; color:#ddd; font-size:14px; line-height:1.8; }}
    .body h2 {{ color:#b8a6ff; font-size:16px; margin-top:24px; margin-bottom:12px; border-bottom:1px solid rgba(255,255,255,0.06); padding-bottom:8px; }}
    .body p {{ margin:0 0 16px; }}
    .footer {{ padding:20px 32px; text-align:center; font-size:11px; color:#666; border-top:1px solid rgba(255,255,255,0.06); }}
    .tarot-section {{ text-align:center; margin:28px 0; padding:20px; background:rgba(255,213,79,0.04); border:1px solid rgba(255,213,79,0.12); border-radius:16px; }}
    .tarot-section img {{ max-width:220px; border-radius:12px; box-shadow:0 8px 32px rgba(124,92,255,0.25); }}
    .tarot-section .card-name {{ color:#ffd54f; font-size:16px; margin-top:12px; font-weight:bold; }}
    .tarot-section .card-meaning {{ color:#c8bfe8; font-size:13px; margin-top:8px; line-height:1.7; }}
</style>
</head>
<body>
    <div class="container">
        <div class="header">
            {logo_html}
            <h1>{dream_title}</h1>
            <p>{ 'For' if lang == 'en' else '致' } {customer_name}</p>
        </div>
        <div class="body">
            {order_html}
            {html_body}
            {cta_html}
        </div>
        <div class="footer">
            {footer_note}<br>
            &copy; 2026 Subconscious Mirror. All rights reserved.
        </div>
    </div>
</body>
</html>"""
    return html

def send_report_content_email(email, report_data, html_body, lang='zh'):
    """Send the full dream report via SMTP."""
    smtp_server = os.environ.get('SMTP_SERVER', '')
    smtp_port = int(os.environ.get('SMTP_PORT', '587'))
    smtp_user = os.environ.get('SMTP_USER', '')
    smtp_password = os.environ.get('SMTP_PASSWORD', '')
    mail_from = os.environ.get('MAIL_FROM', smtp_user)
    mail_from_name = os.environ.get('MAIL_FROM_NAME', 'Subconscious Mirror')

    if not smtp_server or not smtp_user or not smtp_password:
        print("[Email] SMTP credentials not configured")
        return False, "Email service not configured. Please set SMTP_SERVER, SMTP_USER, and SMTP_PASSWORD."

    try:
        subject = report_data.get('dream_title', 'Your Dream Analysis Report' if lang == 'en' else '你的梦境分析报告')
        html = _build_html_email(report_data, html_body, lang)

        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = formataddr((mail_from_name, mail_from))
        msg['To'] = email
        msg.attach(MIMEText(html, 'html', 'utf-8'))

        # Port 465 uses SSL from the start; 587 uses STARTTLS
        if smtp_port == 465:
            with smtplib.SMTP_SSL(smtp_server, smtp_port, timeout=30) as server:
                server.login(smtp_user, smtp_password)
                server.sendmail(mail_from, [email], msg.as_string())
        else:
            with smtplib.SMTP(smtp_server, smtp_port, timeout=30) as server:
                server.starttls()
                server.login(smtp_user, smtp_password)
                server.sendmail(mail_from, [email], msg.as_string())

        print(f"[Email] Report sent to {email}")
        return True, None
    except Exception as e:
        print(f"[Email] Failed to send report: {e}")
        return False, str(e)

# Backwards-compatible aliases used elsewhere
send_order_confirmation = send_report_content_email
send_dream_report = send_report_content_email
send_inactive_reengagement_email = send_report_content_email
